### ISSUE TITLE
Package Name and Fingerprint

### ISSUE THREAD

**Issue by jurgenhaas** [NetworksAreMadeOfString/ZenPacks.rhybudd.alerts#1]
Hi, when I try to get to get my own API Key and Sender ID from GCM, I need to have the package name and fingerprint of the app on my android. They explain that I can get them by using keytool but I guess that means I had to root my device. Is that correct or is there another way to get those two values?

Thanks a lot and hey, I love your effort with this tool. It's amazing.

**Comment by NetworksAreMadeOfString** [comment]
Hi, apologies I had notifications disabled and missed this.

The package name is; net.networksaremadeofstring.rhybudd

I'll get the finger print tonight (don't have access to the key where I am at the moment)

**Comment by NetworksAreMadeOfString** [comment]
BTW you shouldn't have to authorize the app itself as it just uses the SenderID (aka the project ID) instead you need to create a Server Key (since it is Zenoss that is sending the message).

Let me know if that helps.

**Comment by jurgenhaas** [comment]
Hmm, now I'm confused. The form on my Zenoss server asks for GCM Sender ID and a GCM API Key. So what exactly should I be creating and which values should I use for those two fields then?

**Comment by NetworksAreMadeOfString** [comment]
## **To get the SenderID;**
1. Open the Google Cloud Console _( https://cloud.google.com/console# )_
2. If you haven't created an API project yet, click Create Project.
3. Supply a project name and click Create.
4. Once the project has been created, a page appears that displays your project ID and project number. For example, Project Number: 670330094152.
5. Copy down your project number. This is the GCM sender ID.

## **To get a Server API Key:**
1. Within the project created in 2. above select "APIs &auth" from the left hand menu
2. Select Registered apps
3. Tap the red "Register App" button at the top
4. Give the "app" a name (e.g. the hostname of your Zenoss server - it isn't important) and ensure "Web Application" is selected 
5. Tap register
6. Once the pay has loaded expand the section labelled "Server Key" Your API key is shown and will look like **AIzaSyAxP..............................h6ZsWz_o** this is your GCM API Key
7. For security you may want to set the allowed IP addresses to be that of your Zenoss Server

## **To Ensure your API Key is enabled for Google Cloud Message**
1. Select "APIs and Auth" from the left hand menu
2. Find "Google Cloud Messaging for Android" and toggle it to on

**Comment by jurgenhaas** [comment]
Thanks, that worked.

**Comment by NetworksAreMadeOfString** [comment]
Cool :)
